# Generated by Django 5.2 on 2025-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('location', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'country')},
        ),
    ]
