# Generated by Django 5.2 on 2025-04-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_date_recorded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weather.location')),
            ],
        ),
    ]
